import XCTest
import Score

/// Full end-to-end simulation tests ported from Java FullSimulationTests.
/// These tests verify exact CHF amounts after running complete simulations.
final class FullSimulationTests: XCTestCase {

    func testAlongExcel() {
        var companyBuilder = SimulationBuilder.builder().name("A Company").simulationName("Full simulation").numberOfSimulationSteps(12)
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 13000000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 3), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 4), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 5), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 6), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 7), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 8), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 9), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 10), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 11), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 12), 1000)
        let company = companyBuilder.build()
        var activeSimulationStep = company.simulation.getActiveSimulationStep()
        while let step = activeSimulationStep {
            let companySimulationStep = step.getCompanySimulationStep(for: company)
            companySimulationStep.finish()
            activeSimulationStep = company.simulation.getActiveSimulationStep()
        }
        let endOfYear = YearMonth.of(2020, 12).atEndOfMonth()
        XCTAssertEqual(Money.of("CHF", 5320000.00), company.accounting.getBankBalance(endOfYear))
        XCTAssertEqual(Money.of("CHF", -13000000.00), company.accounting.getLongTermDebt(endOfYear))
        XCTAssertEqual(Money.of("CHF", 2665673.44), company.accounting.getRealEstateBalance(endOfYear))
        XCTAssertEqual(Money.of("CHF", 8800000.00), company.accounting.getRevenues(endOfYear))
        XCTAssertEqual(Money.of("CHF", -4657926.56), company.accounting.getPnL(endOfYear))
        XCTAssertEqual(Money.of("CHF", -32605485.89), company.accounting.getCompanyValue(endOfYear))
        XCTAssertEqual(Money.of("CHF", 396000.00), company.accounting.getRawMaterialBalance(endOfYear))
        XCTAssertEqual(Money.of("CHF", -39600.00), company.accounting.getProductBalance(endOfYear))
    }

    func testOneCompanyThreeSteps() {
        var companyBuilder = SimulationBuilder.builder().name("A Company").simulationName("Full simulation").numberOfSimulationSteps(3)
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 3110000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        let company = companyBuilder.build()
        var activeSimulationStep = company.simulation.getActiveSimulationStep()
        while let step = activeSimulationStep {
            let companySimulationStep = step.getCompanySimulationStep(for: company)
            companySimulationStep.finish()
            activeSimulationStep = company.simulation.getActiveSimulationStep()
        }
        let endOfApril = YearMonth.of(2020, 4).atEndOfMonth()
        XCTAssertEqual(Money.of("CHF", -1484611.52), company.accounting.getPnL(endOfApril))
        XCTAssertEqual(Money.of("CHF", -1484611.52), company.accounting.getOwnersCapital(endOfApril))
        XCTAssertEqual(Money.of("CHF", -10392280.66), company.accounting.getCompanyValue(endOfApril))
    }

    func testOneCompanyTwelveSteps() {
        var companyBuilder = SimulationBuilder.builder().name("A Company").simulationName("Full simulation").numberOfSimulationSteps(12)
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 33600000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 3), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 4), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 5), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 6), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 7), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 8), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 9), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 10), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 11), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 12), 1000)
        let company = companyBuilder.build()
        var activeSimulationStep = company.simulation.getActiveSimulationStep()
        while let step = activeSimulationStep {
            let companySimulationStep = step.getCompanySimulationStep(for: company)
            companySimulationStep.finish()
            activeSimulationStep = company.simulation.getActiveSimulationStep()
        }
        let endOfYear = YearMonth.of(2020, 12).atEndOfMonth()
        XCTAssertEqual(11000, company.getSoldProducts())
        XCTAssertEqual(Money.of("CHF", -5687926.56), company.accounting.getPnL(endOfYear))
        XCTAssertEqual(Money.of("CHF", -5687926.56), company.accounting.getOwnersCapital(endOfYear))
        XCTAssertEqual(Money.of("CHF", -39815485.89), company.accounting.getCompanyValue(endOfYear))
    }

    func testTenYearsInYearSteps() {
        let companyBuilder = SimulationBuilder.builder().name("A Ten Year Company").simulationName("Full simulation for ten years").numberOfSimulationSteps(120).passiveSteps(12)
        companyBuilder.increaseCreditLine(.of(2020, 3), Money.of("CHF", 100000000))
        companyBuilder.buildStorage(.of(2020, 6), 10000)
        companyBuilder.buyRawMaterial(.of(2020, 9), 10000)
        companyBuilder.buildFactory(.of(2020, 12))
        companyBuilder.enterMarket(.of(2021, 3))
        companyBuilder.increaseCreditLine(.of(2021, 6), Money.of("CHF", 100000000))
        companyBuilder.buyRawMaterial(.of(2022, 8), 10000)
        let company = companyBuilder.build()
        var activeSimulationStep = company.simulation.getActiveSimulationStep()
        var activeStepCounter = 0
        while let step = activeSimulationStep {
            activeStepCounter += 1
            let companySimulationStep = step.getCompanySimulationStep(for: company)
            companySimulationStep.finish()
            activeSimulationStep = company.simulation.getActiveSimulationStep()
        }
        let endDate = YearMonth.of(2030, 1).atEndOfMonth()
        XCTAssertEqual(Money.of("CHF", 16768000), company.accounting.getRevenues(endDate))
        XCTAssertEqual(10, activeStepCounter)
        XCTAssertEqual(120, company.companySimulationSteps.count)
        XCTAssertEqual(120, company.simulation.simulationSteps.count)
    }

    func testTwoCompaniesEquallyTwelveSteps() {
        var companyBuilder = SimulationBuilder.builder().name("A Company").simulationName("Full simulation").numberOfSimulationSteps(12)
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 33600000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 3), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 4), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 5), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 6), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 7), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 8), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 9), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 10), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 11), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 12), 1000)
        let companyA = companyBuilder.build()
        companyBuilder = SimulationBuilder.builder().simulation(companyA.simulation).name("B Company")
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 33600000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 3), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 4), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 5), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 6), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 7), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 8), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 9), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 10), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 11), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 12), 1000)
        let companyB = companyBuilder.build()
        var activeSimulationStep = companyA.simulation.getActiveSimulationStep()
        while let step = activeSimulationStep {
            step.getCompanySimulationStep(for: companyA).finish()
            step.getCompanySimulationStep(for: companyB).finish()
            activeSimulationStep = companyA.simulation.getActiveSimulationStep()
        }
        let endOfYear = YearMonth.of(2020, 12).atEndOfMonth()
        XCTAssertEqual(10000, companyA.getSoldProducts())
        XCTAssertEqual(Money.of("CHF", -6220326.56), companyA.accounting.getPnL(endOfYear))
        XCTAssertEqual(Money.of("CHF", -6220326.56), companyA.accounting.getOwnersCapital(endOfYear))
        XCTAssertEqual(Money.of("CHF", -43542285.89), companyA.accounting.getCompanyValue(endOfYear))
        XCTAssertEqual(10000, companyB.getSoldProducts())
        XCTAssertEqual(Money.of("CHF", -6220326.56), companyB.accounting.getPnL(endOfYear))
        XCTAssertEqual(Money.of("CHF", -6220326.56), companyB.accounting.getOwnersCapital(endOfYear))
        XCTAssertEqual(Money.of("CHF", -43542285.89), companyB.accounting.getCompanyValue(endOfYear))
    }

    func testTwoCompaniesFierceCompetitionTwelveSteps() {
        var companyBuilder = SimulationBuilder.builder().name("A Company").simulationName("Full simulation").numberOfSimulationSteps(12).laborForce(10000)
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 33600000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 3), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 4), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 5), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 6), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 7), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 8), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 9), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 10), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 11), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 12), 1000)
        let companyA = companyBuilder.build()
        companyBuilder = SimulationBuilder.builder().simulation(companyA.simulation).name("B Company")
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 33600000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 3), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 4), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 5), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 6), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 7), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 8), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 9), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 10), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 11), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 12), 1000)
        companyBuilder = companyBuilder.changeAmountAndPriceOrder(.of(2020, 6), 1000, Money.of("CHF", 30))
        let companyB = companyBuilder.build()
        var activeSimulationStep = companyA.simulation.getActiveSimulationStep()
        while let step = activeSimulationStep {
            step.getCompanySimulationStep(for: companyA).finish()
            step.getCompanySimulationStep(for: companyB).finish()
            activeSimulationStep = companyA.simulation.getActiveSimulationStep()
        }
        XCTAssertEqual(416, companyA.getSoldProducts())
        XCTAssertEqual(832, companyB.getSoldProducts())
    }

    func testTwoCompaniesTwelveStepsIncreaseQuality() {
        var companyBuilder = SimulationBuilder.builder().name("A Company").simulationName("Full simulation").numberOfSimulationSteps(12)
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 33600000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 3), 1000)
        companyBuilder = companyBuilder.increaseQuality(.of(2020, 4), Money.of("CHF", 100000))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 4), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 5), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 6), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 7), 1000)
        companyBuilder = companyBuilder.marketingCampaign(.of(2020, 7), Money.of("CHF", 100000))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 8), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 9), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 10), 1000)
        companyBuilder = companyBuilder.increaseProductivity(.of(2020, 10), Money.of("CHF", 100000))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 11), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 12), 1000)
        let companyA = companyBuilder.build()
        companyBuilder = SimulationBuilder.builder().simulation(companyA.simulation).name("B Company")
        companyBuilder = companyBuilder.increaseCreditLine(.of(2020, 1), Money.of("CHF", 33600000))
        companyBuilder = companyBuilder.buildStorage(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 1), 1000)
        companyBuilder = companyBuilder.buildFactory(.of(2020, 1))
        companyBuilder = companyBuilder.enterMarket(.of(2020, 1))
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 3), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 4), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 5), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 6), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 7), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 8), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 9), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 10), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 11), 1000)
        companyBuilder = companyBuilder.buyRawMaterial(.of(2020, 12), 1000)
        let companyB = companyBuilder.build()
        var activeSimulationStep = companyA.simulation.getActiveSimulationStep()
        while let step = activeSimulationStep {
            step.getCompanySimulationStep(for: companyA).finish()
            step.getCompanySimulationStep(for: companyB).finish()
            activeSimulationStep = companyA.simulation.getActiveSimulationStep()
        }
        let endOfYear = YearMonth.of(2020, 12).atEndOfMonth()
        XCTAssertEqual(10000, companyA.getSoldProducts())
        XCTAssertEqual(Money.of("CHF", -6520326.56), companyA.accounting.getPnL(endOfYear))
        XCTAssertEqual(Money.of("CHF", -6520326.56), companyA.accounting.getOwnersCapital(endOfYear))
        XCTAssertEqual(Money.of("CHF", -45642285.89), companyA.accounting.getCompanyValue(endOfYear))
        XCTAssertEqual(10000, companyB.getSoldProducts())
        XCTAssertEqual(Money.of("CHF", -6220326.56), companyB.accounting.getPnL(endOfYear))
        XCTAssertEqual(Money.of("CHF", -6220326.56), companyB.accounting.getOwnersCapital(endOfYear))
        XCTAssertEqual(Money.of("CHF", -43542285.89), companyB.accounting.getCompanyValue(endOfYear))
    }
}
